---
title: "Random pipelines"
author: Anton Antonov
output: html_notebook
---

```{r, include=FALSE}
library(ERTMon)
library(magrittr)
```

# Introduction

# Random pipelines making

```{r}
set.seed(342)

numberOfPipelines <- 300

testData <- ERTMonSimpleTestData( numberOfEntities = 4, numberOfVariables = 5, 
                                  timeInterval = 900, numberOfTimeCells = 12, randomStartTimesQ = T, 
                                  variableFunction = "random", exportDirectoryName = NULL)

testData2 <- ERTMonSimpleTestData( numberOfEntities = 2, numberOfVariables = 5, 
                                   timeInterval = 900, numberOfTimeCells = 12, randomStartTimesQ = T, 
                                   variableFunction = "random", exportDirectoryName = NULL)
```

```{r}
formulaSpecDF <- 
  data.frame( 
    "FormulaID" = c(1),
    "TermID" = c(1,1,1,2,2), 
    "TermCoefficient" = c( 0.5, 0.5, 0.5, 1.2, 1.2),
    "FeatureName" = c("Var.1.Mean", "Var.2.Mean", "Var.3.Mean", "Var.4.Mean", "Var.5.Mean"), 
    "ReduceFunction" = c("+"),
    "Coefficient" = c(1, 2, 3, 1, 1), 
    "Exponent" = c(1.5, 1, 2, 1, 1),
    "RatioPart" = c( "Numerator", "Denominator", "Denominator", "Numerator", "Denominator"),
    stringsAsFactors = FALSE)
```

```{r}
pipelineLevels <-
  list( level1 = c( "ERTMonUnit()", 
                    "ERTMonUnit( testData$EventRecords, testData$EntityAttributes, testData$ComputationSpecification )"),
        level2 = c( "ERTMonSetEventRecords(testData$EventRecords)",
                    "ERTMonSetEntityAttributes(testData$EntityAttributes)",
                    "ERTMonSetComputationSpecification(testData$ComputationSpecification)" ),
        level3 = c( "ERTMonProcessEventRecords( echoStepsQ = FALSE )", 
                    "ERTMonProcessEventRecords( alignmentSpec = 'MinTime', echoStepsQ = FALSE )", 
                    "ERTMonProcessEventRecords( alignmentSpec = min(testData$EventRecords$ObservationTime), echoStepsQ = FALSE )" ),
        level4 = c( "ERTMonExtractFeatures( testData2$EventRecords, testData2$EntityAttributes, echoStepsQ = FALSE )", 
                    "ERTMonExtractFeatures( testData2$EventRecords, testData2$EntityAttributes, testData2$ComputationSpecification )",
                    "ERTMonTakeFeatureMatrix()",
                    "ERTMonComputeFormula(formulaSpecDF)" ) 
  )
```

```{r}
randomPipelines <- 
  purrr::map( 1:numberOfPipelines, 
              function(x) { 
                rp <- Reduce( function(a,x) { c( a, sample(x,1) )}, init = c(), x = pipelineLevels ) 
                parse( text = paste( rp, collapse = " %>% " ))
              })
```

```{r}
system.time(
  ertRes <- purrr::map( randomPipelines, purrr::safely(eval))
)
```

```{r}
checkRes <- purrr::map_lgl( ertRes, function(x) is.na(x$result) || is.list(x$result) && class(x$result) == "ERTMon" )
```

```{r}
summary(checkRes)
```
```{r}
mean(is.na(purrr::map( ertRes, "result")))
```


